# Generated by Django 3.0.2 on 2020-03-06 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprintbacklogID', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('priority', models.CharField(max_length=5)),
                ('hours', models.PositiveIntegerField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sprint_backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('dueDate', models.DateField(default=datetime.date.today)),
                ('name', models.TextField(default='Sprint Name')),
            ],
        ),
        migrations.CreateModel(
            name='task_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprintbacklogID', models.PositiveIntegerField(default=0)),
                ('productbacklogID', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('assignTo', models.PositiveIntegerField(default=0)),
                ('assignToName', models.CharField(default='None', max_length=50)),
                ('dateCompleted', models.DateField(blank=True)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Incomplete', max_length=10)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name of User', max_length=50)),
                ('role', models.CharField(default='User Role', max_length=50)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
