# Generated by Django 3.0.2 on 2020-02-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('priority', models.PositiveIntegerField()),
                ('hours', models.PositiveIntegerField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprintbacklogID', models.PositiveIntegerField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sprint_backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productbacklogID', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('status', models.PositiveIntegerField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tasks_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprintbacklogID', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('responsible', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
