# Generated by Django 3.0.2 on 2020-02-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks_model',
            new_name='task_model',
        ),
    ]
