# Generated by Django 3.0.2 on 2020-02-29 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='dateCompleted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
