# Generated by Django 3.0.2 on 2020-02-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0002_auto_20200210_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_backlog',
            name='priority',
            field=models.CharField(max_length=5),
        ),
    ]
