# Generated by Django 3.0.2 on 2020-02-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0002_auto_20200228_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='dateCompleted',
            field=models.DateField(blank=True),
        ),
    ]
