# Generated by Django 3.0.2 on 2020-03-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0003_auto_20200228_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='assignToName',
            field=models.CharField(default='Name of User', max_length=15),
        ),
    ]
