# Generated by Django 3.0.2 on 2020-02-20 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0003_auto_20200212_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint_backlog',
            old_name='productbacklogID',
            new_name='sprintID',
        ),
        migrations.RenameField(
            model_name='task_model',
            old_name='responsible',
            new_name='assignTo',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='sprintbacklogID',
        ),
        migrations.RemoveField(
            model_name='sprint_backlog',
            name='status',
        ),
        migrations.AddField(
            model_name='product_backlog',
            name='sprintID',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprint',
            name='dueDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
