# Generated by Django 3.0.2 on 2020-02-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0004_auto_20200219_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='dueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='startDate',
            field=models.DateField(),
        ),
    ]
