# Generated by Django 3.0.2 on 2020-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0004_task_model_assigntoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='assignToName',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
