# Generated by Django 3.0.2 on 2020-03-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0005_auto_20200301_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='assignToName',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='name',
            field=models.CharField(default='Name of User', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='role',
            field=models.CharField(default='User Role', max_length=50),
        ),
    ]
