# Generated by Django 3.0.2 on 2020-02-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0005_auto_20200219_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='assignTo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
