# Generated by Django 3.0.2 on 2020-03-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0006_auto_20200304_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
