# Generated by Django 3.0.2 on 2020-02-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0008_sprint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.TextField(default='Sprint Name', max_length=25),
        ),
    ]
