# Generated by Django 3.0.2 on 2020-02-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0009_auto_20200224_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.TextField(default='Sprint Name'),
        ),
    ]
