# Generated by Django 3.0.2 on 2020-02-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0010_auto_20200224_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='name',
            field=models.CharField(default='Name of User', max_length=15),
        ),
    ]
