# Generated by Django 3.0.2 on 2020-02-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0011_user_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint_backlog',
            name='productbacklogID',
        ),
    ]
