# Generated by Django 3.0.2 on 2020-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0012_remove_sprint_backlog_productbacklogid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sprint',
        ),
        migrations.RenameField(
            model_name='product_backlog',
            old_name='sprintID',
            new_name='sprintbacklogID',
        ),
        migrations.RemoveField(
            model_name='sprint_backlog',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='sprint_backlog',
            name='sprintID',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='username',
        ),
        migrations.AddField(
            model_name='sprint_backlog',
            name='dueDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sprint_backlog',
            name='name',
            field=models.TextField(default='Sprint Name'),
        ),
        migrations.AddField(
            model_name='sprint_backlog',
            name='startDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task_model',
            name='dateCompleted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task_model',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task_model',
            name='productbacklogID',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_model',
            name='role',
            field=models.CharField(default='User Role', max_length=15),
        ),
        migrations.AlterField(
            model_name='sprint_backlog',
            name='content',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='sprintbacklogID',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
