# Generated by Django 3.0.2 on 2020-02-28 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0014_remove_sprint_backlog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint_backlog',
            name='dueDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sprint_backlog',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
