# Generated by Django 3.0.2 on 2020-02-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0015_auto_20200227_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='status',
            field=models.CharField(default='Incomplete', max_length=10),
        ),
    ]
